//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Addresses_DBs2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Integrated Security=SSPI;Data Source=DESKTOP-FT093DB\\SQLEXPRESS;Initial Catalog=N" +
            "amesAddresses;")]
        public string NamesAddresses_SQLDB_ConnectionString {
            get {
                return ((string)(this["NamesAddresses_SQLDB_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost")]
        public string NamesAddresses_MongoDB_ConnectionString {
            get {
                return ((string)(this["NamesAddresses_MongoDB_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NamesAddressesDB")]
        public string NamesAddresses_MongoDB_DatabaseName {
            get {
                return ((string)(this["NamesAddresses_MongoDB_DatabaseName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NamesAddresses")]
        public string NamesAddresses_MongoDB_CollectionName {
            get {
                return ((string)(this["NamesAddresses_MongoDB_CollectionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Addresses_DBs\\NamesAddressesDB.xml")]
        public string NamesAddresses_XmlDB_File {
            get {
                return ((string)(this["NamesAddresses_XmlDB_File"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Addresses_DBs\\NamesAddressesDB.csv")]
        public string NamesAddresses_CsvDB_File {
            get {
                return ((string)(this["NamesAddresses_CsvDB_File"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Addresses_DBs\\NamesAddressesDB.json")]
        public string NamesAddresses_JsonDB_File {
            get {
                return ((string)(this["NamesAddresses_JsonDB_File"]));
            }
        }
    }
}
